name: Deploy to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: your-docker-username/your-image-name:pipeline

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
      - name: Configure kubectl
        uses: steebchen/kubectl@v3
        with:
          kubeconfig: ${{ secrets.KUBE_CONFIG_DATA }}
      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f path/to/your/deployment.yaml
          kubectl apply -f path/to/your/service.yaml
